### ISSUE TITLE
Create Navbar component

### ISSUE THREAD

**Issue by detnos** [detnos/pokemon-react-app#9]
This will house the buttons to view the grocery list, the collection, the search bar, the view all button, and the battle button (if we get to it).  Each button will affect the main display component to show what has been clicked.

**Comment by taylorjason** [comment]
172d15ff390c7c4c60cb2a8688e64a4f2fcb72eb
Core functionality

**Comment by taylorjason** [comment]
e013bd4fe7aa5d62bdf04183a6a2879d7e01220f
Added search bar into nav-bar
